// Производитель товара по марке в названии: «Fanta 1 л» → Coca-Cola. По нему каталог группирует товары
// категории в карточки компаний. Правила проверяются по порядку, первое совпадение побеждает.
// Товары без известной марки остаются без компании и показываются в группе «Другие».

export const COMPANIES: [company: string, match: RegExp][] = [
  // напитки
  ['Coca-Cola', /coca|кока|fanta|фанта|sprite|спрайт|bonaqua|бонаква|fuse ?tea|schweppes|швепс|piko|пико|burn\b|powerade/i],
  ['PepsiCo', /pepsi|пепси|mirinda|миринда|7 ?up|lipton ice|aqua minerale|adrenaline|lay'?s|лейс|cheetos|читос|doritos|daritos|хрусteam|хрус team|добрый/i],
  ['Tassay', /tassay|тассай/i],
  ['Асу (RG Brands)', /\basu\b|асу\b|da-?da|дада|gracio|piala|пиала|maxi|макси|tiger|kazakhstan rg/i],
  ['Turan', /turan|туран/i],
  ['Borjomi', /borjomi|боржоми/i],
  ['Sary-Agash', /сарыагаш|saryagash/i],
  ['Red Bull', /red ?bull/i],
  ['Gorilla', /gorilla|горилла/i],
  ['Dizzy', /dizzy|диззи/i],
  ['Holiday', /holiday/i],
  ['Juicy', /juicy/i],
  ['Rich', /\brich\b/i],
  ['Palma', /palma|пальма/i],
  ['Efes', /efes|эфес|белый медведь|kozel|старый мельник|золотая бочка|velkopopovicky/i],
  ['Carlsberg', /carlsberg|балтика|baltika|tuborg|жигулевское|большая кружка|kronenbourg|holsten/i],
  ['Шымкентпиво', /шымкент|шымкентпиво/i],
  // молочное
  ['Food Master', /food ?master|фуд ?мастер|био-?с\b|bio-?s\b/i],
  ['Айс', /\bайс\b|ais\b/i],
  ['Adal', /adal|адал/i],
  ['Danone', /danone|данон|активиа|actimel|растишка/i],
  ['Milky Land', /milky ?land|милки ?ленд/i],
  ['Президент', /president|президент/i],
  ['Hochland', /hochland|хохланд/i],
  ['Простоквашино', /простоквашино/i],
  ['Домик в деревне', /домик в деревне/i],
  ['Fruttis', /fruttis|фруттис/i],
  ['Alpenland', /alpenland/i],
  ['Савушкин', /савушкин/i],
  ['Зенченко', /зенченко/i],
  ['Айналайын', /айналайын/i],
  ['Родина', /родина/i],
  // сладости
  ['Mars', /snickers|сникерс|\bmars\b|марс\b|twix|твикс|bounty|баунти|milky ?way|orbit|орбит|m&m|skittles|скитлс|whiskas|kitekat|pedigree|dove\b(?=.*шок)|extra\b/i],
  ['Nestlé', /nescaf|нескаф|nesquik|несквик|kit ?kat|киткат|maggi|магги|nestle|нестле|nestogen|gerber|nuts\b|lion\b|bon pari|бон пари|nan\b/i],
  ['Mondelēz', /alpen ?gold|альпен|milka|милка|oreo|орео|\btuc\b|dirol|дирол|юбилейное|барни|halls|холлс|picnic|пикник|toblerone|cadbury/i],
  ['Ferrero', /kinder|киндер|raffaello|рафаэлло|nutella|нутелла|tic ?tac|ferrero|ферреро/i],
  ['Рахат', /рахат|rakhat/i],
  ['Баян Сулу', /bayan ?sulu|баян ?сулу|баянсулу/i],
  ['Конфил', /конфил/i],
  ['Яшкино', /яшкино/i],
  ['Roshen', /roshen|рошен/i],
  ['KDV', /кириешки|яшкино|kdv|ozera|озера|сухарики 3 корочки|3 корочки/i],
  ['Акконд', /акконд/i],
  ['Chupa Chups', /chupa|чупа/i],
  ['Mentos', /mentos|ментос/i],
  ['Orion', /orion|орион|choco ?pie|чоко ?пай/i],
  ['Lotte', /lotte|лотте/i],
  ['Kovis', /kovis|ковис/i],
  ['Bahroma', /bahroma|бахрома/i],
  ['Шин Лайн', /шин ?лайн|shin ?line/i],
  ['Мартукское', /мартук/i],
  ['Инмарко', /инмарко|золотой стандарт|магнат|эскимо инмарко/i],
  // бакалея и консервы
  ['Махеевъ', /махеев/i],
  ['Три желания', /3 желания|три желания/i],
  ['Calvé', /calve|кальве/i],
  ['Heinz', /heinz|хайнц/i],
  ['Knorr', /knorr|кнорр/i],
  ['Makfa', /makfa|макфа/i],
  ['Султан', /султан|sultan/i],
  ['Корона', /корона/i],
  ['Granum', /granum|гранум/i],
  ['Цесна', /цесна|tsesna/i],
  ['Barilla', /barilla|барилла/i],
  ['Роллтон', /rollton|роллтон/i],
  ['Доширак', /доширак|dosirak|doshirak/i],
  ['Big Bon', /big ?bon|биг ?бон/i],
  ['Олейна', /олейна|oleina/i],
  ['Шедевр', /шедевр/i],
  ['Злато', /злато/i],
  ['Bonduelle', /bonduelle|бондюэль/i],
  ['Lorado', /lorado|лорадо/i],
  ['Globus', /globus|глобус/i],
  ['Кублей', /кублей|kublei/i],
  ['Asyl', /asyl|асыл/i],
  ['Royal Food', /royal food|роял фуд/i],
  ['Leonardo', /leonardo/i],
  ['Хрутка', /хрутка/i],
  // чай и кофе
  ['Jacobs', /jacobs|якобс|carte noire|карт нуар|jockey|жокей|monarch/i],
  ['MacCoffee', /maccoffee|маккофе/i],
  ['Ахмад', /ahmad|ахмад/i],
  ['Lipton', /lipton|липтон/i],
  ['Greenfield', /greenfield|гринфилд|tess\b|тесс\b|принцесса/i],
  ['Пиала', /пиала|piala/i],
  ['Ассам', /ассам|assam/i],
  ['Жамбо', /жамбо|jambo/i],
  ['Симба', /симба|simba/i],
  ['Champion', /champion|чемпион/i],
  ['Bassire', /bassire/i],
  // местные и другие марки
  ['Омега', /омега|omega/i],
  ['Увелка', /увелка/i],
  ['Гудвилл', /гудвилл|goodwill/i],
  ['Пассим', /пассим|passim/i],
  ['Promo', /\bpromo\b/i],
  ['Salus', /salus/i],
  ['Сайрам', /сайрам/i],
  ['Эрманн', /эрмигурт|ehrmann|эрманн/i],
  ['Конти', /albeni|альбени|konti|конти|bonjour|бонжур/i],
  ['Del Mar', /del ?mar|дель ?мар/i],
  ['Балтимор', /балтимор|baltimor/i],
  ['Astoria', /astoria|астория/i],
  ['Слобода', /слобода|ряба/i],
  ['Gallina Blanca', /gallina|галина бланка/i],
  ['Preston', /preston/i],
  ['Beerka', /beerka|beerка/i],
  ['Бриджтаун', /flint|флинт/i],
  ['Джинн', /джинн/i],
  ['Qyzyq', /qyzyq/i],
  ['Halley', /halley/i],
  ['Confectum', /confectum/i],
  ['Porleo', /porleo/i],
  ['Кухмастер', /кухмастер/i],
  ['Экопак', /экопак/i],
  ['Мишкино', /мишкино/i],
  ['DEP', /\bdep\b/i],
  // табак
  ['JTI', /winston|винстон|camel|кэмел|ld\b|sobranie|собрание|glamour|гламур|mevius|monte carlo/i],
  ['Philip Morris', /parliament|парламент|marlboro|мальборо|chesterfield|l&m|bond\b|бонд\b|heets|terea|fiit|iqos/i],
  ['BAT', /kent\b|кент\b|rothmans|ротманс|dunhill|vogue|pall mall|glo\b/i],
  ['KT&G', /esse\b|эссе\b/i],
  ['Chapman', /chapman|чапман/i],
  // гигиена и бытовая химия
  ['Procter & Gamble', /tide|тайд|ariel|ариэль|fairy|фейри|pantene|пантин|head ?&? ?shoulders|always|олвейс|gillette|жиллет|lenor|ленор|\bмиф\b|safeguard|сейфгард|old spice|pampers|памперс|blend-?a-?med|oral-?b|naturella|натурелла|discreet|vanish|comet|комет/i],
  ['Unilever', /rexona|рексона|\bdove\b|дав\b|clear\b|клеар|domestos|доместос|axe\b|cif\b|сиф\b|чистая линия|timotei|sunsilk|signal\b|бархатные ручки/i],
  ['Colgate-Palmolive', /colgate|колгейт|palmolive|палмолив|protex|sanex/i],
  ['Henkel', /persil|персил|losk|лоск|pril|bimax|бимакс|schauma|шаума|syoss|gliss|глисс|taft|тафт/i],
  ['Kimberly-Clark', /huggies|хаггис|kotex|котекс|kleenex/i],
  ['Nivea', /nivea|нивея/i],
  ['Garnier', /garnier|гарньер|elseve|эльсев|fructis|фруктис/i],
  ['Johnson & Johnson', /johnson|джонсон|o\.?b\.?\b/i],
  ['Duru', /duru|дуру/i],
  ['Ola', /\bola\b|ола!/i],
  ['Sanfor', /sanfor|санфор/i],
  ['Grass', /\bgrass\b/i],
  ['Aura', /\baura\b/i],
  ['Zewa', /zewa|зева/i],
  ['Familia', /familia|фамилия/i],
  ['Paclan', /paclan|паклан/i],
  ['Duracell', /duracell|дюраселл/i],
  ['Varta', /varta|варта/i],
  ['Raid', /\braid\b|рейд/i],
  ['Glade', /glade|глейд/i],
];

// \b в JavaScript понимает только латиницу: для «Айс», «Асу» граница слова задаётся через буквы Юникода
const BOUNDARY = String.raw`(?:(?<=[\p{L}\p{N}])(?![\p{L}\p{N}])|(?<![\p{L}\p{N}])(?=[\p{L}\p{N}]))`;
const RULES = COMPANIES.map(([company, re]) => [company, new RegExp(re.source.replaceAll(String.raw`\b`, BOUNDARY), 'iu')] as const);

/** Компания-производитель по названию товара; пустая строка — марка не распознана. */
export function companyOf(name: string): string {
  return RULES.find(([, re]) => re.test(name))?.[0] ?? '';
}
